project_name: huskycat
description: HuskyCat AI agent - tri-VCS sync configuration
source:
  url: https://gitlab.com/tinyland/ai/huskycat.git
  platform: gitlab
gitlab:
  url: https://gitlab.com
  token_var: GITLAB_TOKEN
github:
  token_var: GITHUB_TOKEN
  api_url: https://api.github.com
forgejo:
  url: https://codeberg.org
  token_var: FORGEJO_TOKEN
downstream:
  repository_configs:
    - url: https://github.com/tinyland-inc/tinyland-huskycat
      strategy: "auto"
      privacy_mode: "strict"
      branch_mapping:
        main: main
    - url: https://codeberg.org/tinyland/huskycat
      strategy: "auto"
      privacy_mode: "strict"
      token_var: FORGEJO_TOKEN
      branch_mapping:
        main: main
  force_continue: true
  strategy: "auto"
  privacy_mode: "strict"
  commit_messages:
    forward_commit_msg:
      enabled: true
      mode: "latest"
    canned_messages:
      enabled: true
      rotation: "deterministic"
      messages:
        - "chore(sync): integrate upstream changes"
        - "chore(sync): merge upstream updates"
        - "chore(sync): pull latest from upstream"
        - "chore(sync): synchronize with upstream repository"
      signature: "OutBot ∈ Tinyland ꒰ᐢ⸝⸝•༝•⸝⸝ᐢ꒱"
ignore_patterns:
  files:
    - '*.md'
    - '*.log'
    - '*.tmp'
    - .env
    - .env.*
    - '*.secret'
    - '*.kdbx'
    - '*.key'
    - '*.pem'
    - '*.pyc'
    - .DS_Store
    - .secrets.baseline
  directories:
    - __pycache__
    - '*.egg-info'
    - .pytest_cache
    - .mypy_cache
    - .ruff_cache
    - node_modules
    - .idea
    - .vscode
    - .cursor
    - .ai
    - .claude
    - .claude-flow
    - memory
    - dist
    - htmlcov*
    - .github
auto_strip_venvs: true
outbot_as:
  name: "Jess Sullivan"
  email: "jess@sulliwood.org"
  sign_off: true
protect_upstreamers:
  enabled: true
  strip_authors: true
  clean_ai_messages: true
  ai_patterns:
    - 'Co-Authored-By: Claude.*'
    - 'Generated with \[Claude Code\].*'
    - 'Generated by GitHub Copilot'
  squash_mode: none
protect_comments:
  enabled: true
  include_patterns:
    - "*.py"
    - "*.js"
    - "*.ts"
    - "*.yaml"
    - "*.yml"
    - "*.toml"
    - "*.sh"
  exclude_patterns:
    - "LICENSE"
    - "LICENSE.*"
  preserve_docstrings: true
  preserve_shebangs: true
  on_error: "warn"
directory_zones:
  enabled: true
  source: "auto"
  auto_zone_settings:
    group_root_files: true
    root_files_zone_name: "root"
    commit_prefix_template: "chore({zone})"
    exclude_zones: [".git", "node_modules", "__pycache__", ".venv", "dist"]
  skip_unchanged_zones: true
facets:
  enabled: true
  validate_before_sync: true
  license:
    enabled: true
    fail_on_incompatible: false
  language:
    enabled: true
    suggest_zones: true
  metadata:
    enabled: true
    sync_description: true
    sync_topics: true
    sync_homepage: true
    sync_visibility: false
    sync_archived: false
  releases:
    enabled: true
    mirror_releases: true
    include_assets: true

safety_checks:
  enabled: true
  fail_on_error: true
  fail_on_critical: true
  empty_file_detection:
    enabled: true
    blocking: true
  drastic_loc_change:
    enabled: true
    blocking: true
    thresholds:
      overall_warning: 30
      overall_error: 50
      overall_critical: 80
  critical_file_deletion:
    enabled: true
    blocking: true
    critical_files:
      - "LICENSE"
      - "pyproject.toml"
      - "package.json"
  binary_file_corruption:
    enabled: true
    blocking: true
  symlink_safety:
    enabled: true
    blocking: true
